AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB Table for Terraform State Locking with PAY_PER_REQUEST

Resources:
  TerraformStateLockTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "TerraformStateLock"
      BillingMode: PAY_PER_REQUEST # Set billing mode to On-Demand
      AttributeDefinitions:
        - AttributeName: "LockID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "LockID"
          KeyType: "HASH"
